import { sign } from "./lib.mjs";
import { execSync } from "node:child_process";
const A="00000000-0000-0000-0000-00000000000a", B="00000000-0000-0000-0000-00000000000b", C="00000000-0000-0000-0000-00000000000c";
const HOTEL="10000000-0000-0000-0000-00000000000a", TAXI="10000000-0000-0000-0000-00000000000b", ROOM="20000000-0000-0000-0000-00000000000a";
const sql=(q)=>execSync(`su postgres -c "psql -d spot2 -At -F'|' -c \\"${q.replace(/"/g,'\\\\\\"')}\\""`).toString().trim();
const anon=sign({role:"anon"}); const u=(sub)=>sign({sub,role:"authenticated"});
const rest=async(m,path,tok,body)=>{ const r=await fetch("http://127.0.0.1:54321/rest/v1/"+path,{method:m,headers:{apikey:anon,authorization:"Bearer "+tok,"content-type":"application/json",prefer:"return=representation"},body:body?JSON.stringify(body):undefined}); const t=await r.text(); return {status:r.status,txt:t}; };
let pass=0,fail=0; const ok=(n,c,x="")=>{ if(c){pass++;console.log("  ✅",n)} else {fail++;console.log("  ❌",n,x)} };
console.log("\n=== Segurança via API real (o que o browser consegue fazer) ===");
let r=await rest("POST","room_reservations",u(C),{business_id:HOTEL,room_id:ROOM,client_user_id:C,client_name:"C",client_phone:"1",check_in:"2026-11-01",check_out:"2026-11-02",guests:1,nights:1,total_price:2000,commission_amount:0,status:"confirmed"});
ok("cliente NÃO cria reserva de quarto à mão (sem pagar)", r.status>=400, r.status+r.txt);
r=await rest("POST","table_reservations",u(C),{business_id:HOTEL,client_user_id:C,client_name:"C",client_phone:"1",reservation_date:"2026-11-01",time_slot:"19:00",guests:1,status:"confirmed"});
ok("cliente NÃO cria reserva de mesa à mão", r.status>=400, r.status+r.txt);
r=await rest("POST","payments",u(A),{business_id:HOTEL,merchant_ref:"HACK1",plan_id:"premium",amount:900,method:"zumbopay",status:"confirmed",expires_at:new Date(Date.now()+600000).toISOString()});
ok("dono NÃO cria pagamento já confirmado", r.status>=400, r.status+r.txt);
r=await rest("PATCH",`businesses?id=eq.${HOTEL}`,u(A),{plan_id:"premium",plan_status:"active",verified:true});
ok("dono tenta virar premium/verificado → revertido pelo trigger", sql(`select plan_id||'/'||verified from businesses where id='${HOTEL}'`)==="free/false", sql(`select plan_id||'/'||verified from businesses where id='${HOTEL}'`));
r=await rest("PATCH",`businesses?id=eq.${TAXI}`,u(B),{accepts_room_reservation:true,accepts_table_reservation:true});
ok("TÁXI liga reservas pela API → continua desligado", sql(`select accepts_room_reservation||'/'||accepts_table_reservation from businesses where id='${TAXI}'`)==="false/false");
r=await rest("POST","business_rooms",u(B),{business_id:TAXI,name:"Quarto",price_per_night:100,capacity:1});
ok("TÁXI NÃO cria quartos pela API", r.status>=400, r.status+r.txt);
r=await rest("GET","payments?select=id",anon);
ok("anónimo não lê pagamentos", r.status>=400 || r.txt==="[]", r.status+r.txt.slice(0,80));
r=await rest("GET","payments?select=id",u(C));
ok("cliente não lê pagamentos de outros", r.txt==="[]", r.txt.slice(0,80));
r=await rest("PATCH",`room_reservations?id=eq.00000000-0000-0000-0000-000000000000`,u(C),{status:"confirmed"});
ok("cliente não consegue confirmar reservas (update)", r.txt==="[]"||r.status>=400, r.txt.slice(0,80));
r=await rest("GET","admins?select=id",u(C)); ok("cliente não vê a tabela de admins", r.txt==="[]"||r.status>=400, r.txt.slice(0,60));
console.log(`RESULTADO segurança API: ${pass} ok, ${fail} falhas`);
