import {
  MapPin,
  Search,
  MessageCircle,
  User,
  Store,
  Compass,
  Utensils,
  Coffee,
  Pill,
  Hotel,
  ShoppingCart,
  Sparkles,
  Beer,
  Stethoscope,
  Map as MapIcon,
  Home,
  Scissors,
  Phone,
  Heart,
  Flame,
  Star,
  Clock,
  Navigation,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Check,
  Send,
  Plus,
  Bell,
  Shield,
  HelpCircle,
  Globe,
  Lock,
  Briefcase,
  Plane,
  Camera,
  Car,
  Wrench,
  ShoppingBag,
  Smartphone,
  Plug,
  Shirt,
  Image as ImageIcon,
  BarChart3,
  Megaphone,
  Tag,
  CalendarClock,
  Mail,
  Apple,
  ArrowRight,
  ArrowLeft,
  LogOut,
  Building2,
  Eye,
  MousePointerClick,
  PhoneCall,
  MessageSquare,
  Wine,
  Palette,
  Bed,
  Waves,
  Music,
  Wifi,
  Crown,
  BadgeCheck,
  Circle,
  QrCode,
  Pencil,
  AlertTriangle,
  X,
  Download,
  Copy,
  Flag,
  ThumbsUp,
  FileText,
  Truck,
  Paperclip,
  Mic,
  TrendingUp,
  Info,
  type LucideIcon,
  Minus,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  // brand / nav
  pin: MapPin,
  search: Search,
  chat: MessageCircle,
  user: User,
  compass: Compass,
  store: Store,
  building: Building2,
  briefcase: Briefcase,
  // categories
  restaurant: Utensils,
  cafe: Coffee,
  pharmacy: Pill,
  hotel: Hotel,
  supermarket: ShoppingCart,
  beauty: Palette,
  bar: Beer,
  clinic: Stethoscope,
  tourism: MapIcon,
  rental: Home,
  barber: Scissors,
  sparkles: Sparkles,
  wine: Wine,
  pizza: Utensils,
  hotel_restaurant: Bed,
  // interests
  food: Utensils,
  health: Pill,
  leisure: Waves,
  shopping: ShoppingBag,
  nightlife: Wine,
  transport: Car,
  services: Wrench,
  hotels: Hotel,
  online_clothes: Shirt,
  online_mobile: Smartphone,
  online_appliances: Plug,
  other: Plus,
  // actions / status
  phone: Phone,
  heart: Heart,
  flame: Flame,
  star: Star,
  clock: Clock,
  navigation: Navigation,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trendingUp: TrendingUp,
  info: Info,
  check: Check,
  send: Send,
  plus: Plus,
  minus: Minus,
  cart: ShoppingCart,
  bell: Bell,
  shield: Shield,
  help: HelpCircle,
  globe: Globe,
  lock: Lock,
  mail: Mail,
  apple: Apple,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  logout: LogOut,
  eye: Eye,
  click: MousePointerClick,
  phoneCall: PhoneCall,
  message: MessageSquare,
  image: ImageIcon,
  chart: BarChart3,
  megaphone: Megaphone,
  tag: Tag,
  schedule: CalendarClock,
  plane: Plane,
  camera: Camera,
  music: Music,
  wifi: Wifi,
  crown: Crown,
  verified: BadgeCheck,
  dot: Circle,
  qr: QrCode,
  pencil: Pencil,
  alert: AlertTriangle,
  x: X,
  download: Download,
  copy: Copy,
  flag: Flag,
  thumbsUp: ThumbsUp,
  fileText: FileText,
  transporter: Car,
  delivery: Truck,
  paperclip: Paperclip,
  mic: Mic,
};

interface Props extends React.SVGAttributes<SVGSVGElement> {
  name: string;
  size?: number;
}

export function Icon({ name, size = 18, className, ...rest }: Props) {
  const C = MAP[name] ?? Circle;
  return <C size={size} className={className} strokeWidth={2} {...rest} />;
}

export const ICON_NAMES = Object.keys(MAP);
