/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReservationsDashboardRouteImport } from './routes/reservations-dashboard'
import { Route as ReservationSettingsRouteImport } from './routes/reservation-settings'
import { Route as QrBusinessRouteImport } from './routes/qr-business'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PublishPostRouteImport } from './routes/publish-post'
import { Route as PublishEventRouteImport } from './routes/publish-event'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyReservationsRouteImport } from './routes/my-reservations'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as MapRouteImport } from './routes/map'
import { Route as ManageRoomsRouteImport } from './routes/manage-rooms'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as BusinessInboxRouteImport } from './routes/business-inbox'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsBusinessIdRouteImport } from './routes/rooms.$businessId'
import { Route as ReviewsIdRouteImport } from './routes/reviews.$id'
import { Route as ReserveTableBusinessIdRouteImport } from './routes/reserve-table.$businessId'
import { Route as ReserveRoomRoomIdRouteImport } from './routes/reserve-room.$roomId'
import { Route as PlaceIdRouteImport } from './routes/place.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as BusinessPromoRouteImport } from './routes/business.promo'
import { Route as BusinessOrdersRouteImport } from './routes/business.orders'
import { Route as BusinessCouponsRouteImport } from './routes/business.coupons'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsDashboardRoute = ReservationsDashboardRouteImport.update({
  id: '/reservations-dashboard',
  path: '/reservations-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationSettingsRoute = ReservationSettingsRouteImport.update({
  id: '/reservation-settings',
  path: '/reservation-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QrBusinessRoute = QrBusinessRouteImport.update({
  id: '/qr-business',
  path: '/qr-business',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishPostRoute = PublishPostRouteImport.update({
  id: '/publish-post',
  path: '/publish-post',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishEventRoute = PublishEventRouteImport.update({
  id: '/publish-event',
  path: '/publish-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReservationsRoute = MyReservationsRouteImport.update({
  id: '/my-reservations',
  path: '/my-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoomsRoute = ManageRoomsRouteImport.update({
  id: '/manage-rooms',
  path: '/manage-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessInboxRoute = BusinessInboxRouteImport.update({
  id: '/business-inbox',
  path: '/business-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsBusinessIdRoute = RoomsBusinessIdRouteImport.update({
  id: '/rooms/$businessId',
  path: '/rooms/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveTableBusinessIdRoute = ReserveTableBusinessIdRouteImport.update({
  id: '/reserve-table/$businessId',
  path: '/reserve-table/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoomRoomIdRoute = ReserveRoomRoomIdRouteImport.update({
  id: '/reserve-room/$roomId',
  path: '/reserve-room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdRoute = PlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPromoRoute = BusinessPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessOrdersRoute = BusinessOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCouponsRoute = BusinessCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => BusinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/boost': typeof BoostRoute
  '/business': typeof BusinessRouteWithChildren
  '/business-inbox': typeof BusinessInboxRoute
  '/chats': typeof ChatsRoute
  '/events': typeof EventsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/manage-rooms': typeof ManageRoomsRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/my-reservations': typeof MyReservationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/publish-event': typeof PublishEventRoute
  '/publish-post': typeof PublishPostRoute
  '/qr': typeof QrRoute
  '/qr-business': typeof QrBusinessRoute
  '/reservation-settings': typeof ReservationSettingsRoute
  '/reservations-dashboard': typeof ReservationsDashboardRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/business/coupons': typeof BusinessCouponsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/promo': typeof BusinessPromoRoute
  '/chat/$id': typeof ChatIdRoute
  '/place/$id': typeof PlaceIdRoute
  '/reserve-room/$roomId': typeof ReserveRoomRoomIdRoute
  '/reserve-table/$businessId': typeof ReserveTableBusinessIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/rooms/$businessId': typeof RoomsBusinessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/boost': typeof BoostRoute
  '/business': typeof BusinessRouteWithChildren
  '/business-inbox': typeof BusinessInboxRoute
  '/chats': typeof ChatsRoute
  '/events': typeof EventsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/manage-rooms': typeof ManageRoomsRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/my-reservations': typeof MyReservationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/publish-event': typeof PublishEventRoute
  '/publish-post': typeof PublishPostRoute
  '/qr': typeof QrRoute
  '/qr-business': typeof QrBusinessRoute
  '/reservation-settings': typeof ReservationSettingsRoute
  '/reservations-dashboard': typeof ReservationsDashboardRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/business/coupons': typeof BusinessCouponsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/promo': typeof BusinessPromoRoute
  '/chat/$id': typeof ChatIdRoute
  '/place/$id': typeof PlaceIdRoute
  '/reserve-room/$roomId': typeof ReserveRoomRoomIdRoute
  '/reserve-table/$businessId': typeof ReserveTableBusinessIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/rooms/$businessId': typeof RoomsBusinessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/boost': typeof BoostRoute
  '/business': typeof BusinessRouteWithChildren
  '/business-inbox': typeof BusinessInboxRoute
  '/chats': typeof ChatsRoute
  '/events': typeof EventsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/manage-rooms': typeof ManageRoomsRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/my-reservations': typeof MyReservationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/publish-event': typeof PublishEventRoute
  '/publish-post': typeof PublishPostRoute
  '/qr': typeof QrRoute
  '/qr-business': typeof QrBusinessRoute
  '/reservation-settings': typeof ReservationSettingsRoute
  '/reservations-dashboard': typeof ReservationsDashboardRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/business/coupons': typeof BusinessCouponsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/promo': typeof BusinessPromoRoute
  '/chat/$id': typeof ChatIdRoute
  '/place/$id': typeof PlaceIdRoute
  '/reserve-room/$roomId': typeof ReserveRoomRoomIdRoute
  '/reserve-table/$businessId': typeof ReserveTableBusinessIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/rooms/$businessId': typeof RoomsBusinessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/boost'
    | '/business'
    | '/business-inbox'
    | '/chats'
    | '/events'
    | '/history'
    | '/home'
    | '/manage-rooms'
    | '/map'
    | '/merchant'
    | '/my-reservations'
    | '/onboarding'
    | '/payment'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/publish-event'
    | '/publish-post'
    | '/qr'
    | '/qr-business'
    | '/reservation-settings'
    | '/reservations-dashboard'
    | '/search'
    | '/subscribe'
    | '/business/coupons'
    | '/business/orders'
    | '/business/promo'
    | '/chat/$id'
    | '/place/$id'
    | '/reserve-room/$roomId'
    | '/reserve-table/$businessId'
    | '/reviews/$id'
    | '/rooms/$businessId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/boost'
    | '/business'
    | '/business-inbox'
    | '/chats'
    | '/events'
    | '/history'
    | '/home'
    | '/manage-rooms'
    | '/map'
    | '/merchant'
    | '/my-reservations'
    | '/onboarding'
    | '/payment'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/publish-event'
    | '/publish-post'
    | '/qr'
    | '/qr-business'
    | '/reservation-settings'
    | '/reservations-dashboard'
    | '/search'
    | '/subscribe'
    | '/business/coupons'
    | '/business/orders'
    | '/business/promo'
    | '/chat/$id'
    | '/place/$id'
    | '/reserve-room/$roomId'
    | '/reserve-table/$businessId'
    | '/reviews/$id'
    | '/rooms/$businessId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/boost'
    | '/business'
    | '/business-inbox'
    | '/chats'
    | '/events'
    | '/history'
    | '/home'
    | '/manage-rooms'
    | '/map'
    | '/merchant'
    | '/my-reservations'
    | '/onboarding'
    | '/payment'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/publish-event'
    | '/publish-post'
    | '/qr'
    | '/qr-business'
    | '/reservation-settings'
    | '/reservations-dashboard'
    | '/search'
    | '/subscribe'
    | '/business/coupons'
    | '/business/orders'
    | '/business/promo'
    | '/chat/$id'
    | '/place/$id'
    | '/reserve-room/$roomId'
    | '/reserve-table/$businessId'
    | '/reviews/$id'
    | '/rooms/$businessId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BoostRoute: typeof BoostRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  BusinessInboxRoute: typeof BusinessInboxRoute
  ChatsRoute: typeof ChatsRoute
  EventsRoute: typeof EventsRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  ManageRoomsRoute: typeof ManageRoomsRoute
  MapRoute: typeof MapRoute
  MerchantRoute: typeof MerchantRoute
  MyReservationsRoute: typeof MyReservationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  PublishEventRoute: typeof PublishEventRoute
  PublishPostRoute: typeof PublishPostRoute
  QrRoute: typeof QrRoute
  QrBusinessRoute: typeof QrBusinessRoute
  ReservationSettingsRoute: typeof ReservationSettingsRoute
  ReservationsDashboardRoute: typeof ReservationsDashboardRoute
  SearchRoute: typeof SearchRoute
  SubscribeRoute: typeof SubscribeRoute
  ChatIdRoute: typeof ChatIdRoute
  PlaceIdRoute: typeof PlaceIdRoute
  ReserveRoomRoomIdRoute: typeof ReserveRoomRoomIdRoute
  ReserveTableBusinessIdRoute: typeof ReserveTableBusinessIdRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
  RoomsBusinessIdRoute: typeof RoomsBusinessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations-dashboard': {
      id: '/reservations-dashboard'
      path: '/reservations-dashboard'
      fullPath: '/reservations-dashboard'
      preLoaderRoute: typeof ReservationsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation-settings': {
      id: '/reservation-settings'
      path: '/reservation-settings'
      fullPath: '/reservation-settings'
      preLoaderRoute: typeof ReservationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-business': {
      id: '/qr-business'
      path: '/qr-business'
      fullPath: '/qr-business'
      preLoaderRoute: typeof QrBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-post': {
      id: '/publish-post'
      path: '/publish-post'
      fullPath: '/publish-post'
      preLoaderRoute: typeof PublishPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-event': {
      id: '/publish-event'
      path: '/publish-event'
      fullPath: '/publish-event'
      preLoaderRoute: typeof PublishEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reservations': {
      id: '/my-reservations'
      path: '/my-reservations'
      fullPath: '/my-reservations'
      preLoaderRoute: typeof MyReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-rooms': {
      id: '/manage-rooms'
      path: '/manage-rooms'
      fullPath: '/manage-rooms'
      preLoaderRoute: typeof ManageRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-inbox': {
      id: '/business-inbox'
      path: '/business-inbox'
      fullPath: '/business-inbox'
      preLoaderRoute: typeof BusinessInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$businessId': {
      id: '/rooms/$businessId'
      path: '/rooms/$businessId'
      fullPath: '/rooms/$businessId'
      preLoaderRoute: typeof RoomsBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve-table/$businessId': {
      id: '/reserve-table/$businessId'
      path: '/reserve-table/$businessId'
      fullPath: '/reserve-table/$businessId'
      preLoaderRoute: typeof ReserveTableBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve-room/$roomId': {
      id: '/reserve-room/$roomId'
      path: '/reserve-room/$roomId'
      fullPath: '/reserve-room/$roomId'
      preLoaderRoute: typeof ReserveRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$id': {
      id: '/place/$id'
      path: '/place/$id'
      fullPath: '/place/$id'
      preLoaderRoute: typeof PlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/promo': {
      id: '/business/promo'
      path: '/promo'
      fullPath: '/business/promo'
      preLoaderRoute: typeof BusinessPromoRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/orders': {
      id: '/business/orders'
      path: '/orders'
      fullPath: '/business/orders'
      preLoaderRoute: typeof BusinessOrdersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/coupons': {
      id: '/business/coupons'
      path: '/coupons'
      fullPath: '/business/coupons'
      preLoaderRoute: typeof BusinessCouponsRouteImport
      parentRoute: typeof BusinessRoute
    }
  }
}

interface BusinessRouteChildren {
  BusinessCouponsRoute: typeof BusinessCouponsRoute
  BusinessOrdersRoute: typeof BusinessOrdersRoute
  BusinessPromoRoute: typeof BusinessPromoRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessCouponsRoute: BusinessCouponsRoute,
  BusinessOrdersRoute: BusinessOrdersRoute,
  BusinessPromoRoute: BusinessPromoRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  BoostRoute: BoostRoute,
  BusinessRoute: BusinessRouteWithChildren,
  BusinessInboxRoute: BusinessInboxRoute,
  ChatsRoute: ChatsRoute,
  EventsRoute: EventsRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  ManageRoomsRoute: ManageRoomsRoute,
  MapRoute: MapRoute,
  MerchantRoute: MerchantRoute,
  MyReservationsRoute: MyReservationsRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  PublishEventRoute: PublishEventRoute,
  PublishPostRoute: PublishPostRoute,
  QrRoute: QrRoute,
  QrBusinessRoute: QrBusinessRoute,
  ReservationSettingsRoute: ReservationSettingsRoute,
  ReservationsDashboardRoute: ReservationsDashboardRoute,
  SearchRoute: SearchRoute,
  SubscribeRoute: SubscribeRoute,
  ChatIdRoute: ChatIdRoute,
  PlaceIdRoute: PlaceIdRoute,
  ReserveRoomRoomIdRoute: ReserveRoomRoomIdRoute,
  ReserveTableBusinessIdRoute: ReserveTableBusinessIdRoute,
  ReviewsIdRoute: ReviewsIdRoute,
  RoomsBusinessIdRoute: RoomsBusinessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
