/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QrBusinessRouteImport } from './routes/qr-business'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as MapRouteImport } from './routes/map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as BusinessInboxRouteImport } from './routes/business-inbox'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIdRouteImport } from './routes/reviews.$id'
import { Route as PlaceIdRouteImport } from './routes/place.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as BusinessOrdersRouteImport } from './routes/business.orders'
import { Route as BusinessCouponsRouteImport } from './routes/business.coupons'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QrBusinessRoute = QrBusinessRouteImport.update({
  id: '/qr-business',
  path: '/qr-business',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessInboxRoute = BusinessInboxRouteImport.update({
  id: '/business-inbox',
  path: '/business-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdRoute = PlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOrdersRoute = BusinessOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCouponsRoute = BusinessCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => BusinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/boost': typeof BoostRoute
  '/business': typeof BusinessRouteWithChildren
  '/business-inbox': typeof BusinessInboxRoute
  '/chats': typeof ChatsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/qr-business': typeof QrBusinessRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/business/coupons': typeof BusinessCouponsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/chat/$id': typeof ChatIdRoute
  '/place/$id': typeof PlaceIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/boost': typeof BoostRoute
  '/business': typeof BusinessRouteWithChildren
  '/business-inbox': typeof BusinessInboxRoute
  '/chats': typeof ChatsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/qr-business': typeof QrBusinessRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/business/coupons': typeof BusinessCouponsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/chat/$id': typeof ChatIdRoute
  '/place/$id': typeof PlaceIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/boost': typeof BoostRoute
  '/business': typeof BusinessRouteWithChildren
  '/business-inbox': typeof BusinessInboxRoute
  '/chats': typeof ChatsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/merchant': typeof MerchantRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/qr-business': typeof QrBusinessRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/business/coupons': typeof BusinessCouponsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/chat/$id': typeof ChatIdRoute
  '/place/$id': typeof PlaceIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/boost'
    | '/business'
    | '/business-inbox'
    | '/chats'
    | '/history'
    | '/home'
    | '/map'
    | '/merchant'
    | '/onboarding'
    | '/payment'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/qr'
    | '/qr-business'
    | '/search'
    | '/subscribe'
    | '/business/coupons'
    | '/business/orders'
    | '/chat/$id'
    | '/place/$id'
    | '/reviews/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/boost'
    | '/business'
    | '/business-inbox'
    | '/chats'
    | '/history'
    | '/home'
    | '/map'
    | '/merchant'
    | '/onboarding'
    | '/payment'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/qr'
    | '/qr-business'
    | '/search'
    | '/subscribe'
    | '/business/coupons'
    | '/business/orders'
    | '/chat/$id'
    | '/place/$id'
    | '/reviews/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/boost'
    | '/business'
    | '/business-inbox'
    | '/chats'
    | '/history'
    | '/home'
    | '/map'
    | '/merchant'
    | '/onboarding'
    | '/payment'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/qr'
    | '/qr-business'
    | '/search'
    | '/subscribe'
    | '/business/coupons'
    | '/business/orders'
    | '/chat/$id'
    | '/place/$id'
    | '/reviews/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BoostRoute: typeof BoostRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  BusinessInboxRoute: typeof BusinessInboxRoute
  ChatsRoute: typeof ChatsRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  MerchantRoute: typeof MerchantRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  QrRoute: typeof QrRoute
  QrBusinessRoute: typeof QrBusinessRoute
  SearchRoute: typeof SearchRoute
  SubscribeRoute: typeof SubscribeRoute
  ChatIdRoute: typeof ChatIdRoute
  PlaceIdRoute: typeof PlaceIdRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-business': {
      id: '/qr-business'
      path: '/qr-business'
      fullPath: '/qr-business'
      preLoaderRoute: typeof QrBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-inbox': {
      id: '/business-inbox'
      path: '/business-inbox'
      fullPath: '/business-inbox'
      preLoaderRoute: typeof BusinessInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$id': {
      id: '/place/$id'
      path: '/place/$id'
      fullPath: '/place/$id'
      preLoaderRoute: typeof PlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/orders': {
      id: '/business/orders'
      path: '/orders'
      fullPath: '/business/orders'
      preLoaderRoute: typeof BusinessOrdersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/coupons': {
      id: '/business/coupons'
      path: '/coupons'
      fullPath: '/business/coupons'
      preLoaderRoute: typeof BusinessCouponsRouteImport
      parentRoute: typeof BusinessRoute
    }
  }
}

interface BusinessRouteChildren {
  BusinessCouponsRoute: typeof BusinessCouponsRoute
  BusinessOrdersRoute: typeof BusinessOrdersRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessCouponsRoute: BusinessCouponsRoute,
  BusinessOrdersRoute: BusinessOrdersRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BoostRoute: BoostRoute,
  BusinessRoute: BusinessRouteWithChildren,
  BusinessInboxRoute: BusinessInboxRoute,
  ChatsRoute: ChatsRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  MerchantRoute: MerchantRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  QrRoute: QrRoute,
  QrBusinessRoute: QrBusinessRoute,
  SearchRoute: SearchRoute,
  SubscribeRoute: SubscribeRoute,
  ChatIdRoute: ChatIdRoute,
  PlaceIdRoute: PlaceIdRoute,
  ReviewsIdRoute: ReviewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
